// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiF32ubOFSW3J7xtmEBdRZPmRBWqAVPj4',
    appId: '1:54655812814:web:91e0edd4b98487b6cabc9f',
    messagingSenderId: '54655812814',
    projectId: 'foodjet-cca3d',
    authDomain: 'foodjet-cca3d.firebaseapp.com',
    storageBucket: 'foodjet-cca3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxYqvOBumzah8XATjx_KzjLHwv-GTW0S8',
    appId: '1:54655812814:android:41a59666d6c20ae8cabc9f',
    messagingSenderId: '54655812814',
    projectId: 'foodjet-cca3d',
    storageBucket: 'foodjet-cca3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC79xVSOiIRI_O_njNPwXFDEAbzGl17t8k',
    appId: '1:54655812814:ios:dc019d52a461e979cabc9f',
    messagingSenderId: '54655812814',
    projectId: 'foodjet-cca3d',
    storageBucket: 'foodjet-cca3d.appspot.com',
    iosBundleId: 'com.example.foddJet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC79xVSOiIRI_O_njNPwXFDEAbzGl17t8k',
    appId: '1:54655812814:ios:a1c191b99c61206fcabc9f',
    messagingSenderId: '54655812814',
    projectId: 'foodjet-cca3d',
    storageBucket: 'foodjet-cca3d.appspot.com',
    iosBundleId: 'com.example.foddJet.RunnerTests',
  );
}
